In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('../../data/advertising_dataset_regression.csv')

In [4]:
df.head()

TV  radio  newspaper  sales
0  112.4    2.6       16.9    8.8
1  285.2   26.6       27.9   19.9
2  219.6   27.0       17.7   21.6
3  179.6   31.9        8.9   19.1
4   46.8   36.3       12.1   14.5

In [6]:
X = df.drop('sales', axis=1)
y = df['sales']

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [9]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()

In [12]:
scaler.fit(X_train)

StandardScaler()

In [13]:
X_train = scaler.transform(X_train)

In [14]:
X_test = scaler.transform(X_test)

In [15]:
from sklearn.linear_model import Ridge

In [16]:
model = Ridge(alpha = 100)

In [17]:
from sklearn.model_selection import cross_val_score

In [18]:
scores = cross_val_score(model, X_train, y_train, scoring='neg_mean_squared_error', cv=5)

In [19]:
scores

array([-13.00078306,  -9.25913013,  -7.56025917,  -4.27921902,
        -9.05147232])

In [20]:
abs(scores.mean())

np.float64(8.630172738245921)

In [21]:
model = Ridge(alpha = 1)

In [22]:
scores = cross_val_score(model, X_train, y_train, scoring='neg_mean_squared_error', cv=5)

In [23]:
scores

array([-4.81915913, -3.99855409, -2.99696285, -2.80680878, -4.9280166 ])

In [24]:
abs(scores.mean())

np.float64(3.90990028987853)

In [25]:
model = Ridge(alpha = 0.1)

In [26]:
scores = cross_val_score(model, X_train, y_train, scoring='neg_mean_squared_error', cv=5)

In [27]:
scores

array([-4.81142292, -3.98513113, -3.02351711, -2.82903074, -4.90845825])

In [28]:
abs(scores.mean())

np.float64(3.9115120314896465)

In [29]:
model = Ridge(alpha=1)

In [30]:
scores = cross_val_score(model, X_train, y_train, scoring='neg_mean_squared_error', cv=10)

In [31]:
scores

array([-3.00878657, -6.36200334, -3.870638  , -3.97853597, -2.57137306,
       -3.23451654, -2.04292505, -3.55326571, -3.64537451, -6.00897301])

In [32]:
abs(scores.mean())

np.float64(3.827639174196144)

In [33]:
model = Ridge(alpha=0.1)

In [35]:
scores = cross_val_score(model, X_train, y_train, scoring='neg_mean_squared_error', cv=10)

In [36]:
scores

array([-2.99762943, -6.36253955, -3.84050772, -3.98270073, -2.59303016,
       -3.24553907, -2.06953221, -3.56123678, -3.62309892, -5.99575371])

In [37]:
abs(scores.mean())

np.float64(3.8271568276270087)

In [38]:
model.fit(X_train, y_train)

Ridge(alpha=0.1)

In [39]:
y_final_test_prediciton = model.predict(X_test)

In [40]:
from sklearn.metrics import mean_squared_error

In [41]:
mean_squared_error(y_test, y_final_test_prediciton)

3.703765805312635